-- ORDERS table creation script
CREATE TABLE MYLIB.ORDERS (
    ORDER_ID    INTEGER GENERATED ALWAYS AS IDENTITY
                        (START WITH 1 INCREMENT BY 1),
    CUSTOMER_ID CHAR(10) NOT NULL,
    PRODUCT_ID  CHAR(10) NOT NULL,
    QUANTITY    INTEGER NOT NULL,
    ORDER_DATE  DATE NOT NULL,
    STATUS      CHAR(10) NOT NULL,
    PRIMARY KEY (ORDER_ID)
);