-- PRODUCTS table creation script
CREATE TABLE MYLIB.PRODUCTS (
    PRODUCT_ID  CHAR(10) NOT NULL,
    NAME        VARCHAR(50) NOT NULL,
    PRICE       DECIMAL(7,2) NOT NULL,
    IN_STOCK    INTEGER NOT NULL,
    PRIMARY KEY (PRODUCT_ID)
);